// Ad Script Importer - Figma Plugin
// Imports ad scripts from JSON generated by write_scripts_to_figma.py

figma.showUI(__html__, { width: 400, height: 500 });

// Handle messages from UI
figma.ui.onmessage = async (msg) => {
  if (msg.type === 'import-scripts') {
    try {
      const scripts = msg.scripts;
      let successCount = 0;
      let errorCount = 0;
      const errors = [];

      // Process each script
      for (const script of scripts) {
        try {
          // Find text node by layer name
          const nodes = figma.currentPage.findAll(node => {
            return node.type === 'TEXT' && node.name === script.layerName;
          });

          if (nodes.length === 0) {
            errors.push(`Layer not found: ${script.layerName}`);
            errorCount++;
            continue;
          }

          // Update first matching node
          const textNode = nodes[0];

          // Load font before updating text
          await figma.loadFontAsync(textNode.fontName);

          // Update text content
          textNode.characters = script.content;

          successCount++;

          // Optional: Add metadata
          textNode.setPluginData('scriptName', script.scriptName);
          textNode.setPluginData('importedAt', new Date().toISOString());

        } catch (err) {
          errors.push(`Error updating ${script.layerName}: ${err.message}`);
          errorCount++;
        }
      }

      // Send results back to UI
      figma.ui.postMessage({
        type: 'import-complete',
        success: successCount,
        errors: errorCount,
        errorMessages: errors
      });

    } catch (err) {
      figma.ui.postMessage({
        type: 'import-error',
        message: err.message
      });
    }
  } else if (msg.type === 'cancel') {
    figma.closePlugin();
  } else if (msg.type === 'list-text-layers') {
    // List all text layers on current page
    const textLayers = figma.currentPage.findAll(node => node.type === 'TEXT');
    const layerInfo = textLayers.map(layer => ({
      name: layer.name,
      id: layer.id,
      characters: layer.characters.substring(0, 50) + (layer.characters.length > 50 ? '...' : '')
    }));

    figma.ui.postMessage({
      type: 'text-layers-list',
      layers: layerInfo
    });
  }
};
