"""
Export Research Report Tool
============================

Compile a comprehensive research report from multiple data sources.

Purpose:
    Aggregate competitor intelligence, own performance data, and hook analysis
    into a single Markdown report. This is the deliverable that summarises
    the current state of the market and informs creative strategy.

Inputs:
    --competitor_file   Path to competitor ad library JSON
    --performance_file  Path to own performance analysis JSON
    --hooks_file        Path to hooks analysis JSON
    --brand             Brand ID
    --title             Report title (optional)

Outputs:
    Markdown report at .tmp/research/report_{brand}_{date}.md

No MCP Integration:
    Pure Python document generation.
"""

import argparse
import json
import logging
import sys
from datetime import datetime
from pathlib import Path
from typing import Any, Optional

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent
TMP_DIR = BASE_DIR / ".tmp" / "research"
CONFIG_DIR = BASE_DIR / "config"

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger("export_research_report")


# ---------------------------------------------------------------------------
# Data loading helpers
# ---------------------------------------------------------------------------

def load_json_file(filepath: str) -> Optional[dict[str, Any]]:
    """Safely load a JSON file, returning None if not found."""
    path = Path(filepath)
    if not path.exists():
        logger.warning("File not found: %s", filepath)
        return None
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def load_brand_name(brand_id: str) -> str:
    """Load the brand display name."""
    config_path = CONFIG_DIR / "brands.json"
    if config_path.exists():
        with open(config_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        for brand in data.get("brands", []):
            if brand["brand_id"] == brand_id:
                return brand.get("brand_name", brand_id)
    return brand_id


# ---------------------------------------------------------------------------
# Report sections
# ---------------------------------------------------------------------------

def generate_header(brand_name: str, title: Optional[str] = None) -> str:
    """Generate the report header."""
    date_str = datetime.now().strftime("%d %B %Y")
    report_title = title or f"Performance Marketing Research Report - {brand_name}"

    lines = [
        f"# {report_title}",
        "",
        f"**Brand:** {brand_name}",
        f"**Date:** {date_str}",
        f"**Generated by:** Carisma Performance Marketing System",
        "",
        "---",
        "",
    ]
    return "\n".join(lines)


def generate_executive_summary(
    competitor_data: Optional[dict[str, Any]],
    performance_data: Optional[dict[str, Any]],
    hooks_data: Optional[dict[str, Any]],
) -> str:
    """Generate the executive summary section."""
    lines = [
        "## Executive Summary",
        "",
    ]

    points: list[str] = []

    if competitor_data:
        total_ads = competitor_data.get("metadata", {}).get("total_ads_found", 0)
        points.append(f"- Analysed **{total_ads}** competitor ads from the Meta Ad Library")

    if performance_data:
        summary = performance_data.get("summary", {})
        total_spend = summary.get("total_spend", 0)
        total_leads = summary.get("total_leads", 0)
        overall_cpl = summary.get("overall_cpl")
        cpl_target = summary.get("cpl_target")
        on_target = summary.get("on_target", False)

        points.append(
            f"- Total spend: **{total_spend:.2f} EUR** generating **{total_leads}** leads"
        )
        if overall_cpl is not None:
            status = "on target" if on_target else "above target"
            points.append(
                f"- Overall CPL: **{overall_cpl:.2f} EUR** "
                f"(target: {cpl_target:.2f} EUR) - {status}"
            )

        breakdown = summary.get("classification_breakdown", {})
        if breakdown:
            winners = breakdown.get("winner", 0)
            losers = breakdown.get("loser", 0)
            points.append(
                f"- Ad classification: {winners} winners, {losers} losers"
            )

    if hooks_data:
        analysis = hooks_data.get("analysis", {})
        unique_hooks = analysis.get("unique_hooks", 0)
        top_category = ""
        cat_dist = analysis.get("category_distribution", {})
        if cat_dist:
            top_category = max(cat_dist, key=lambda k: cat_dist[k])
        points.append(
            f"- Identified **{unique_hooks}** unique hooks "
            f"(top category: {top_category})"
        )

    if not points:
        points.append("- No data files were provided for this report")

    lines.extend(points)
    lines.append("")
    return "\n".join(lines)


def generate_competitor_section(competitor_data: Optional[dict[str, Any]]) -> str:
    """Generate the competitor analysis section."""
    lines = ["## Competitor Analysis", ""]

    if not competitor_data:
        lines.append("*No competitor data available.*")
        lines.append("")
        return "\n".join(lines)

    ads = competitor_data.get("ads", [])
    metadata = competitor_data.get("metadata", {})

    lines.append(f"**Source:** Meta Ad Library ({metadata.get('country', 'MT')})")
    lines.append(f"**Search Terms:** {metadata.get('search_terms', 'N/A')}")
    lines.append(f"**Total Ads Found:** {metadata.get('total_ads_found', len(ads))}")
    lines.append("")

    # Advertiser breakdown
    advertiser_counts: dict[str, int] = {}
    for ad in ads:
        page_name = ad.get("page_name", "Unknown")
        advertiser_counts[page_name] = advertiser_counts.get(page_name, 0) + 1

    if advertiser_counts:
        lines.append("### Active Advertisers")
        lines.append("")
        lines.append("| Advertiser | Active Ads |")
        lines.append("|-----------|------------|")

        sorted_advertisers = sorted(advertiser_counts.items(), key=lambda x: x[1], reverse=True)
        for name, count in sorted_advertisers[:15]:
            lines.append(f"| {name} | {count} |")
        lines.append("")

    # Spend ranges (if available, EU transparency)
    ads_with_spend = [a for a in ads if a.get("spend_lower") or a.get("spend_upper")]
    if ads_with_spend:
        lines.append("### Spend Insights (EU Transparency)")
        lines.append("")

        top_spenders = sorted(
            ads_with_spend,
            key=lambda a: int(a.get("spend_upper") or a.get("spend_lower") or 0),
            reverse=True,
        )[:10]

        lines.append("| Advertiser | Spend Range |")
        lines.append("|-----------|-------------|")
        for ad in top_spenders:
            name = ad.get("page_name", "Unknown")
            lower = ad.get("spend_lower", "?")
            upper = ad.get("spend_upper", "?")
            lines.append(f"| {name} | {lower} - {upper} |")
        lines.append("")

    # Sample creatives
    lines.append("### Sample Ad Copy")
    lines.append("")

    sample_ads = ads[:5]
    for i, ad in enumerate(sample_ads, 1):
        page_name = ad.get("page_name", "Unknown")
        bodies = ad.get("ad_creative_bodies", [])
        body_text = bodies[0] if bodies else "N/A"
        # Truncate long text
        if isinstance(body_text, str) and len(body_text) > 200:
            body_text = body_text[:200] + "..."

        lines.append(f"**{i}. {page_name}:**")
        lines.append(f"> {body_text}")
        lines.append("")

    return "\n".join(lines)


def generate_performance_section(performance_data: Optional[dict[str, Any]]) -> str:
    """Generate the own performance section."""
    lines = ["## Own Performance Analysis", ""]

    if not performance_data:
        lines.append("*No performance data available.*")
        lines.append("")
        return "\n".join(lines)

    summary = performance_data.get("summary", {})
    ads = performance_data.get("ads", [])

    # Overview metrics
    lines.append("### Overview")
    lines.append("")
    lines.append(f"- **Total Ads Analysed:** {summary.get('total_ads_analyzed', 0)}")
    lines.append(f"- **Total Spend:** {summary.get('total_spend', 0):.2f} EUR")
    lines.append(f"- **Total Leads:** {summary.get('total_leads', 0)}")
    lines.append(f"- **Overall CPL:** {summary.get('overall_cpl', 'N/A')}")
    lines.append(f"- **CPL Target:** {summary.get('cpl_target', 'N/A')} EUR")
    lines.append("")

    # Classification breakdown
    breakdown = summary.get("classification_breakdown", {})
    if breakdown:
        lines.append("### Classification Breakdown")
        lines.append("")
        lines.append("| Classification | Count |")
        lines.append("|---------------|-------|")
        for cls, count in breakdown.items():
            lines.append(f"| {cls.replace('_', ' ').title()} | {count} |")
        lines.append("")

    # Top performers
    top = summary.get("top_performers", [])
    if top:
        lines.append("### Top Performers (Scale)")
        lines.append("")
        lines.append("| Ad Name | CPL | Leads |")
        lines.append("|---------|-----|-------|")
        for t in top:
            cpl_display = f"{t['cpl']:.2f} EUR" if t.get("cpl") else "N/A"
            lines.append(f"| {t['name'][:50]} | {cpl_display} | {t.get('leads', 0)} |")
        lines.append("")

    # Worst performers
    worst = summary.get("worst_performers", [])
    if worst:
        lines.append("### Worst Performers (Kill)")
        lines.append("")
        lines.append("| Ad Name | CPL | Spend |")
        lines.append("|---------|-----|-------|")
        for w in worst:
            cpl_display = f"{w['cpl']:.2f} EUR" if w.get("cpl") else "N/A"
            lines.append(f"| {w['name'][:50]} | {cpl_display} | {w.get('spend', 0):.2f} EUR |")
        lines.append("")

    return "\n".join(lines)


def generate_hooks_section(hooks_data: Optional[dict[str, Any]]) -> str:
    """Generate the hooks analysis section."""
    lines = ["## Hook Analysis", ""]

    if not hooks_data:
        lines.append("*No hooks data available.*")
        lines.append("")
        return "\n".join(lines)

    analysis = hooks_data.get("analysis", {})

    lines.append(f"**Total Texts Analysed:** {analysis.get('total_texts_analyzed', 0)}")
    lines.append(f"**Unique Hooks Found:** {analysis.get('unique_hooks', 0)}")
    lines.append("")

    # Category distribution
    cat_dist = analysis.get("category_distribution", {})
    if cat_dist:
        lines.append("### Hook Categories")
        lines.append("")
        lines.append("| Category | Count |")
        lines.append("|----------|-------|")
        for cat, count in sorted(cat_dist.items(), key=lambda x: x[1], reverse=True):
            lines.append(f"| {cat.replace('_', ' ').title()} | {count} |")
        lines.append("")

    # Top hooks
    hooks = analysis.get("hooks", [])
    if hooks:
        lines.append("### Top Hooks by Score")
        lines.append("")
        for i, hook in enumerate(hooks[:10], 1):
            lines.append(
                f"{i}. **[{hook.get('primary_category', 'general')}]** "
                f"\"{hook['hook_text'][:100]}\" "
                f"(score: {hook.get('score', 0)}, freq: {hook.get('frequency', 0)})"
            )
        lines.append("")

    return "\n".join(lines)


def generate_recommendations(
    performance_data: Optional[dict[str, Any]],
    hooks_data: Optional[dict[str, Any]],
) -> str:
    """Generate actionable recommendations section."""
    lines = ["## Recommendations", ""]

    recommendations: list[str] = []

    if performance_data:
        summary = performance_data.get("summary", {})
        recs = summary.get("recommendation_breakdown", {})

        scale_count = recs.get("scale", 0)
        kill_count = recs.get("kill", 0)
        iterate_count = recs.get("iterate", 0)

        if scale_count > 0:
            recommendations.append(
                f"1. **Scale winners:** {scale_count} ads are performing at or below CPL target. "
                "Increase daily budgets by 20-30% and consider duplicating to new audiences."
            )

        if kill_count > 0:
            recommendations.append(
                f"2. **Kill losers:** {kill_count} ads are burning budget above the kill threshold. "
                "Pause immediately and reallocate budget to winners."
            )

        if iterate_count > 0:
            recommendations.append(
                f"3. **Iterate on marginals:** {iterate_count} ads show promise but need optimisation. "
                "Test new hooks, refine targeting, or improve landing page experience."
            )

    if hooks_data:
        analysis = hooks_data.get("analysis", {})
        cat_dist = analysis.get("category_distribution", {})
        if cat_dist:
            top_cat = max(cat_dist, key=lambda k: cat_dist[k])
            recommendations.append(
                f"4. **Hook strategy:** '{top_cat.replace('_', ' ')}' hooks are most common. "
                "Test underrepresented categories to find untapped angles."
            )

    if not recommendations:
        recommendations.append("No specific recommendations available. Gather more data.")

    lines.extend(recommendations)
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Report compilation
# ---------------------------------------------------------------------------

def compile_report(
    competitor_file: Optional[str] = None,
    performance_file: Optional[str] = None,
    hooks_file: Optional[str] = None,
    brand_id: Optional[str] = None,
    title: Optional[str] = None,
) -> str:
    """
    Compile the full research report as Markdown.
    """
    brand_name = load_brand_name(brand_id) if brand_id else "Unknown Brand"

    # Load data files
    competitor_data = load_json_file(competitor_file) if competitor_file else None
    performance_data = load_json_file(performance_file) if performance_file else None
    hooks_data = load_json_file(hooks_file) if hooks_file else None

    # Build report
    sections = [
        generate_header(brand_name, title),
        generate_executive_summary(competitor_data, performance_data, hooks_data),
        generate_competitor_section(competitor_data),
        generate_performance_section(performance_data),
        generate_hooks_section(hooks_data),
        generate_recommendations(performance_data, hooks_data),
    ]

    # Footer
    sections.append("---")
    sections.append("")
    sections.append(
        f"*Report generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} "
        "by the Carisma Performance Marketing System.*"
    )

    return "\n".join(sections)


def save_report(content: str, brand_id: Optional[str]) -> Path:
    """Save the report to .tmp/research/."""
    TMP_DIR.mkdir(parents=True, exist_ok=True)
    date_str = datetime.now().strftime("%Y%m%d")
    brand_slug = brand_id or "all"
    filename = f"report_{brand_slug}_{date_str}.md"
    output_path = TMP_DIR / filename

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)

    logger.info("Report saved to %s", output_path)
    return output_path


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------

def export_research_report(
    competitor_file: Optional[str] = None,
    performance_file: Optional[str] = None,
    hooks_file: Optional[str] = None,
    brand_id: Optional[str] = None,
    title: Optional[str] = None,
) -> dict[str, Any]:
    """
    Generate and save the research report.

    Returns metadata about the generated report.
    """
    report_content = compile_report(
        competitor_file=competitor_file,
        performance_file=performance_file,
        hooks_file=hooks_file,
        brand_id=brand_id,
        title=title,
    )

    output_path = save_report(report_content, brand_id)

    return {
        "metadata": {
            "tool": "export_research_report",
            "brand": brand_id,
            "competitor_file": competitor_file,
            "performance_file": performance_file,
            "hooks_file": hooks_file,
            "output_path": str(output_path),
            "report_length_chars": len(report_content),
            "generated_at": datetime.utcnow().isoformat() + "Z",
        },
        "output_path": str(output_path),
    }


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args(argv: Optional[list[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Compile a comprehensive research report.",
    )
    parser.add_argument("--competitor_file", type=str, default=None, help="Path to competitor data JSON")
    parser.add_argument("--performance_file", type=str, default=None, help="Path to performance analysis JSON")
    parser.add_argument("--hooks_file", type=str, default=None, help="Path to hooks analysis JSON")
    parser.add_argument("--brand", type=str, default=None, help="Brand ID")
    parser.add_argument("--title", type=str, default=None, help="Custom report title")
    return parser.parse_args(argv)


def main(argv: Optional[list[str]] = None) -> None:
    args = parse_args(argv)

    try:
        result = export_research_report(
            competitor_file=args.competitor_file,
            performance_file=args.performance_file,
            hooks_file=args.hooks_file,
            brand_id=args.brand,
            title=args.title,
        )

        print(json.dumps(result, indent=2))
        logger.info("Report exported to %s", result["output_path"])

    except Exception as exc:
        logger.exception("Unexpected error: %s", exc)
        sys.exit(2)


if __name__ == "__main__":
    main()
